services:
  db:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    container_name: nano-mm-db
    environment:
      POSTGRES_DB: nano_mm
      POSTGRES_USER: nano_mm
      POSTGRES_PASSWORD: nano_mm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - nano_mm_data:/data
    restart: unless-stopped

volumes:
  pgdata:
  nano_mm_data:
